### PR TITLE
Lab meeting blog for 25 july

### PR DESCRIPTION
**Pull request by KirstieJane**
Accidentally included the blog post from #59 in this PR 🤦‍♀. I'll just aim to merge #59 first and then this one. Sorry for the confusion!

Confirmation from everyone who was mentioned:

- [x] @KirstieJane 
- [x] @maxinemack 
- [x] @pherterich
- [x] @sgibson91
- [x] @GeorgiaHCA 
- [x] @ajrcampbell
- [x] @sparkler0323 
- [x] @minnieho1115 
- [ ] @yochannah
- [x] @Islast 
- [x] @emdupre 
- [x] @LouiseABowler

### CODE REVIEW

**Comment by pherterich** [comment]
:+1: from me

*Edit* I don't think I can officially review..

**Review by sgibson91 — APPROVED** [review]

**Review by Islast — APPROVED** [review]

**Review by emdupre — APPROVED** [review]
:sparkles:

**Review by LouiseABowler — APPROVED** [review]

**Comment by ajrcampbell** [comment]
@KirstieJane 👍(I cannot review)

**Comment by KirstieJane** [comment]
Whoops - on the early merge - but I think we were close enough that we can leave the blogs merged.

**Pull request merged**
