### PR TITLE
Choose a name for BrainNetworksInPython

### PR DESCRIPTION
**Pull request by Islast**
This is the blog suggested in https://github.com/WhitakerLab/BrainNetworksInPython/issues/19. I think it's best to (begin to) address https://github.com/WhitakerLab/BrainNetworksInPython/issues/18 before merging. That way people can check the readme to see what they're voting over :nail_care: . 

Meanwhile, see what you think :woman_cartwheeling:

### CODE REVIEW

**Review by KirstieJane — COMMENTED** [review]
The title is hilaaaaarious! I love it @Islast!! ✨ 

Can you think of a good image to go with it? Blog posts with pictures are much more fun than those without 😄 

I think the beginning of the blog post needs 1 sentence about the goal of the project, and an explicit link to the project ("You can find out more about the project at it's GitHub repository").

I also think it would give people more ideas if you added the 5 options you've seeded the poll with to the blog post, but also encourage the reader to add their own.

**Comment by Islast** [comment]
@KirstieJane I've made the changes you asked for:
* add pictures (too many?)
* add line of explanation about what bnip is
* include our 5 suggestions and encourage people to add their own

Any other feedback? :sparkles:

**Comment by KirstieJane** [comment]
Hi @Islast - I've moved some of the formatting around to get it to look nice once it's rendered. I've also adjusted the words a little bit and added a heading.

Take a look and if it's all ok then go ahead and merge!

**Review by KirstieJane — DISMISSED** [review]
Looks good to me!

**Review by KirstieJane — APPROVED** [review]
Still looks good with the updated date!

**Comment by Islast** [comment]
Whoops-oh-no, I don't have write access here :-1:

**Comment by KirstieJane** [comment]
Merged! From the plane. Really logging off now! 🛫

**Pull request merged**
