### PR TITLE
Isla's first blog post

### PR DESCRIPTION
**Pull request by Islast**
The blog post for my first assignment. Note: Barbara has asked to read this before we put it up, so I have emailed it to her, and I'm waiting for her response :sweat_smile:

### CODE REVIEW

**Comment by KirstieJane** [comment]
Oh my goodness this is fantastic! I love it!



I've added you as an author. Please could you add a few details to the [`_data/authors.yml`](https://github.com/Islast/whitakerlab.github.io/blob/master/_data/authors.yml) file and a picture to the [`images`](https://github.com/Islast/whitakerlab.github.io/blob/master/images) folder.

Once that's done I'll approve and then when Barbara has checked it over you're totally ready to merge 😄

**Review by KirstieJane — DISMISSED** [review]
LOVE IT

**Comment by Islast** [comment]
I've made one minor change that Barbara asked for. And done the authors stuff, everything should be ready to go

**Review by KirstieJane — APPROVED** [review]
Great!

**Comment by KirstieJane** [comment]
Merged!! Thank you!

**Pull request merged**
